### ISSUE TITLE
The dataset splitting method

### ISSUE THREAD

**Issue by HoudaJebbari** [mr7495/COVID-CTset#10]
Hi, I have another COVID dataset and I want to test it on the 'train&validation' classification model you provided. I am wondering how you split your data. 
  - How many images did you choose for each patient of the 77 patients (fold 1, training set, covid) to collect the 1820 images. If you chose the same number of images for each patient, that means (1820/77 =~ 24) -> 24 images per patient? 
  -  Which images did you select? Are they successive images of the patient's CT scan? 
  - Are they in the middle of the CT scan to have the lung fully open?

Thank you in advance.

**Comment by mr7495** [comment]
Hello,
with using the [CT_selection_algorithm](https://github.com/mr7495/COVID-CT-Code/blob/master/CT_selection_algorithm.py) the system will automatically discard the images that inside the lung is not visible on them. (Caution: the parameters of this algorithm are based on our dataset and may need to be changed in other datasets.)
The Ct-scan of each patient infected to COVID-19 has a sequence of successive images. We separated those images that the covid infection are visible and distinguishable in them. Because some Ct scan images of an infected patient may not contain the infection points so if we label them as covid, the model will face trouble in learning. Therefore, there is no a fixed number of images for each patient; one may have five images (showing the infections), and another may have 30 images.

**Comment by HoudaJebbari** [comment]
Thank you for your quick reply. 
I have changed the parameters of [CT_selection_algorithm](https://github.com/mr7495/COVID-CT-Code/blob/master/CT_selection_algorithm.py) to adapt it to the dataset I will use.
So, from what understand, you choose the images showing the infection manually with the help of a radiologist.
thank you for confirming this.

**Comment by mr7495** [comment]
You are welcome! Yes, you are correct.
