### ISSUE TITLE
Images with contrast or transformation effect?

### ISSUE THREAD

**Issue by GMBarra** [mr7495/COVID-CTset#3]
Hi, I was looking at the images of the full dataset and noticed that the images are quite dark and I was wondering if this is because they are images without contrast or it is just a transform effect to make them visible on the screens.

This is what i see:

![image](https://user-images.githubusercontent.com/25462755/99459458-e1d34d80-290c-11eb-8d0c-c5f7254ca1aa.png)

This is what I usually see:

![image](https://user-images.githubusercontent.com/25462755/99459478-ee57a600-290c-11eb-8fe0-d6dab8d5f440.png)

Thanks in advance :).

**Comment by mr7495** [comment]
> Hi, I was looking at the images of the full dataset and noticed that the images are quite dark and I was wondering if this is because they are images without contrast or it is just a transform effect to make them visible on the screens.
> 
> This is what i see:
> 
> ![image](https://user-images.githubusercontent.com/25462755/99459458-e1d34d80-290c-11eb-8d0c-c5f7254ca1aa.png)
> 
> This is what I usually see:
> 
> ![image](https://user-images.githubusercontent.com/25462755/99459478-ee57a600-290c-11eb-8fe0-d6dab8d5f440.png)
> 
> Thanks in advance :).

Hello;
The original Images in our dataset are in TIFF format (16-bit uint type), which contain the same image data as the DICOM format and only do not include the patients metadata. But you can not visualize this TIFF format images with your monitor and they look like completely black images (because standard monitors can not show 16-bit images in uint type). So if you would like to convert these images to visualizable images you can use [This code](https://github.com/mr7495/COVID-CTset/blob/master/Visualize.py).
My suggestion is to use the original images for training or testing the models in order to not lose any data.
Some of the images converted to visualizable format are:
[vis_data.zip](https://github.com/mr7495/COVID-CTset/files/5557624/vis_data.zip)

**Comment by mr7495** [comment]
You can see the in the uploaded zip file that the images are not dark and it only depend on the method you use for converting the original images.

**Comment by GMBarra** [comment]
> You can see the in the uploaded zip file that the images are not dark and it only depend on the method you use for converting the original images.

You are right, it only depends on the conversion method, I tried other methods and it is only a visualization issue that does not affect the training.

thanks! :)
